### ISSUE TITLE
合同算術で暗号化する

### ISSUE THREAD

**Issue by ymsht** [Coniglio/caesar_cipher#1]
[合同算術](https://ja.wikipedia.org/wiki/合同算術)

**Comment by Coniglio** [comment]
https://wikimedia.org/api/rest_v1/media/math/render/svg/e24bbb5b37cbe0590ca74fa2c0f1d15157ed3b8a

**Comment by ymsht** [comment]
![e24bbb5b37cbe0590ca74fa2c0f1d15157ed3b8a](https://user-images.githubusercontent.com/949768/103456675-c943b900-4d3b-11eb-82a7-36c4b2d2c069.png)

**Comment by ymsht** [comment]
https://github.com/Coniglio/caesar_cipher/releases/tag/v1.0.0
